name: wangku
description: A money manager app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_expandable_fab: ^2.0.0
  flutter_native_splash: ^2.3.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  gap: ^3.0.1
  go_router: ^13.0.0
  image_picker: ^1.0.5
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
  uses-material-design: true

flutter_native_splash:
  color: "#FCFCFC"
  image: assets/icons/app-icon.png
  android: true
  ios: true